[package]
name = "scamoku"
version = "0.1.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
displaydoc = "0.1"
# TODO: async
# tokio = { version = "1.2", features = ["full"] }