[package]
name = "scallop-gomoku"
version = "0.1.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
displaydoc = "0.1"